;=======================================
;====  Artix polybar Master Config  ====
;=======================================
;=============================
;====  Colors & Settings  ====
;=============================

;==== gruvbox
;[colors]
;background = #cc282828
;foreground = #d65d0e
;moderate = #ebdbb2
;urgent = #fb4934
;trim = #458588
;blue = #83a598
;pink = #d3869b
;orange = #fe8019
;purple = #b16286
;yellow = #fabd2f
;white = #fbf1c7
;gray = #928374
;green = #b8bb26
;border = #ccd65d0e

;==== nord
;[colors]
;background = #cc2b303b
;foreground = #5E81AC
;moderate = #ebcb8b
;urgent = #D08770
;trim = #81A1C1
;blue = #8fa1b3
;pink = #bf616a
;orange = #ebcb8b
;purple = #b48ead
;yellow = #ebcb8b
;white = #d1d1d1
;gray = #585858
;green = #a3be8c
;border = #5E81AC

;==== dracula
[colors]
background = #cc282A36
foreground = #db93f9
moderate = #ebcb8b
urgent = #ffb86c
trim = #8be9fd
blue = #6272a4
pink = #ff79c6
orange = #ffb86c
purple = #bd93f9
yellow = #f1fa8c
white = #f8f8f2
gray = #585858
green = #50fa7b
border = #ccdb93f9

[settings]
compositing-background = source
compositing-foreground = source
compositing-overline = source
compositing-underline = source
compositing-border = source
screenchange-reload = true
format-foreground = ${colors.foreground}
format-background = ${colors.background}
;pseudo-transparency = true

;======================
;====  Master Bar  ====
;======================

[bar/master]
; Use $ xrandr -q | grep " connected" | cut -d ' ' -f1
monitor = DisplayPort-1
width = 100%
height = 24
border-size = 0
border-top-size = 0
border-bottom-size = 2
;margin-bottom = 1
radius = 0
bottom = false
line-size = 2
enable-ipc = true

;==== font-N = <fontconfig pattern>;<vertical offset>
font-0 = "Roboto:style=Medium:size=10;2"
font-1 = "JetBrainsMono Nerd Font:style=Regular:size=11;2"
font-2 = "Digital Readout Thick Upright:style=Bold:size=18;2"
font-3 = "icomoon:style=Regular:size=11;2"
font-4 = "Material Design Icons:style=Regular:size=11;2"


offset-x = 0
offset-y = 0
fixed-center = true
border-color = ${colors.border}
background = ${colors.background}
foreground = ${colors.foreground}
module-margin = 1
padding-right = 0
padding-left = 0
;separator = %{F#d65d0e}󰇙
separator = 
;scroll-up = pamixer -i 2
;scroll-down = pamixer -d 2
click-middle = skippy-xd --activate-window-picker
double-click-left = networkmanager_dmenu
double-click-middle = skippy-xd --activate-window-picker
double-click-right = pavucontrol &
